
name: Build Goldleaf

on: [push]
jobs:
  Goldleaf:
    runs-on: ubuntu-18.04

    container:
      image: devkitpro/devkita64
      options: --user 1001

    steps:
    - uses: actions/checkout@v1
    - name: Update repo
      run: |
        git submodule update --init --recursive
        
    - name: Build Goldleaf
      run: |
        apt-get install -y fakeroot
        make initial -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: Goldleaf
        path: Goldleaf/Goldleaf.nro
